import SwiftUI
import UIKit

// Generates a one-page PDF sheet for an element and shares it.

enum ElementPDFExporter {
    static func makePDF(for el: PropertyElement) -> URL? {
        let pageW: CGFloat = 612, pageH: CGFloat = 792
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageW, height: pageH))
        let safeName = el.name.components(separatedBy: CharacterSet(charactersIn: "/\\:?%*|\"<>")).joined()
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(safeName.isEmpty ? "element" : safeName).pdf")
        do {
            try renderer.writePDF(to: url) { ctx in
                ctx.beginPage()
                var y: CGFloat = 48
                let left: CGFloat = 48
                let width = pageW - 96

                func draw(_ s: String, font: UIFont, color: UIColor = .black, gap: CGFloat = 8) {
                    let attr: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
                    let bounding = (s as NSString).boundingRect(
                        with: CGSize(width: width, height: .greatestFiniteMagnitude),
                        options: [.usesLineFragmentOrigin], attributes: attr, context: nil)
                    (s as NSString).draw(in: CGRect(x: left, y: y, width: width, height: bounding.height + 4),
                                         withAttributes: attr)
                    y += bounding.height + gap
                }
                func row(_ k: String, _ v: String?) {
                    guard let v, !v.isEmpty else { return }
                    draw("\(k): \(v)", font: .systemFont(ofSize: 13))
                }

                draw(el.name, font: .boldSystemFont(ofSize: 24))
                draw(el.elementType.displayName, font: .systemFont(ofSize: 14), color: .gray, gap: 16)

                if let c = el.coverPhotoUrl, let u = URL(string: c),
                   let d = try? Data(contentsOf: u), let img = UIImage(data: d) {
                    let ratio = img.size.height / max(img.size.width, 1)
                    let h = min(width * ratio, 260)
                    img.draw(in: CGRect(x: left, y: y, width: width, height: h))
                    y += h + 16
                }

                row("Condition", el.technicalCondition.displayName)
                row("Health score", "\(el.healthScore)/100")
                row("Brand", el.brand)
                row("Model", el.model)
                row("Serial", el.serialNumber)
                row("Purchase date", el.purchaseDate)
                row("Warranty until", el.warrantyUntil)
                if let v = el.estimatedValue { row("Estimated value", String(format: "%.0f %@", v, el.valueCurrency)) }
                if el.isElectric {
                    row("Electric", "Yes")
                    row("Automation system", el.automationSystem)
                }
                if !el.tags.isEmpty { row("Tags", el.tags.joined(separator: ", ")) }
                if let d = el.description { draw("", font: .systemFont(ofSize: 4)); row("Description", d) }
                if let n = el.notes { row("Notes", n) }

                draw("", font: .systemFont(ofSize: 8))
                draw("Generated by PRVIO", font: .systemFont(ofSize: 10), color: .lightGray)
            }
            return url
        } catch {
            return nil
        }
    }
}

struct ShareURL: Identifiable {
    let id = UUID()
    let url: URL
}

struct ActivityShareView: UIViewControllerRepresentable {
    let items: [Any]
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }
    func updateUIViewController(_ vc: UIActivityViewController, context: Context) {}
}
