-- 124: Plant OS, phase P2 — encyclopedia + Level 2 (botanical profile).
--
-- A shared, read-mostly botanical knowledge base. Unlike `plants` (which is
-- property-scoped, one row per plant a household owns) `plant_species` is a
-- GLOBAL catalog: one row per species, readable by every authenticated user,
-- seeded by migrations / the service role. A plant links to its encyclopedia
-- entry via plants.species_id.
--
-- Honesty law: every seeded fact below is hand-curated from general botanical
-- references (RHS, Missouri Botanical Garden, Kew — Plants of the World
-- Online). Fields we are not confident about are left NULL rather than
-- invented; the UI renders only populated fields, never placeholders.

create table if not exists public.plant_species (
  id uuid primary key default gen_random_uuid(),

  -- identification
  slug text not null unique,
  common_name text not null,
  latin_name text not null,
  synonyms text[],
  family text,
  genus text,
  species text,
  common_names_ro text[],

  -- natural habitat
  origin text,
  altitude text,
  native_temp text,
  native_humidity text,
  habitat_type text,

  -- characteristics
  max_height text,
  max_width text,
  growth_rate text,
  lifespan text,
  evergreen boolean,
  flowering_period text,
  fruiting text,
  fragrance text,

  -- leaves
  leaf_size text,
  leaf_shape text,
  leaf_colour text,
  leaf_texture text,
  variegation text,
  gloss text,

  -- roots
  root_type text,

  -- guides & lore
  propagation text,
  pruning text,
  seasonal_checklist text[],
  annual_calendar jsonb,   -- { "March": "note", ... }
  faq jsonb,               -- [ { "q": "...", "a": "..." }, ... ]
  myths text[],
  curiosities text[],
  sources text[],

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_plant_species_common on public.plant_species (common_name);

alter table public.plant_species enable row level security;

-- Public read of the catalog for any signed-in user. No insert/update/delete
-- policy: the corpus is curated by migrations / the service role only.
drop policy if exists plant_species_read on public.plant_species;
create policy plant_species_read on public.plant_species
  for select to authenticated
  using (true);

-- Link a plant to its encyclopedia entry (nullable, catalog-scoped so the
-- reference is intentionally NOT cascade-deleted with a household).
alter table public.plants
  add column if not exists species_id uuid references public.plant_species(id);

-- ── Curated seed ─────────────────────────────────────────────────────────
-- On conflict (slug) do nothing so re-running the migration is idempotent.

insert into public.plant_species
  (slug, common_name, latin_name, synonyms, family, genus, species, common_names_ro,
   origin, native_humidity, habitat_type,
   max_height, growth_rate, lifespan, evergreen, flowering_period, fruiting, fragrance,
   leaf_size, leaf_shape, leaf_colour, leaf_texture, variegation, gloss, root_type,
   propagation, pruning, seasonal_checklist, annual_calendar, faq, myths, curiosities, sources)
values
  ('monstera-deliciosa', 'Swiss cheese plant', 'Monstera deliciosa',
   ARRAY['Split-leaf philodendron','Ceriman','Fruit salad plant'],
   'Araceae', 'Monstera', 'deliciosa', ARRAY['Monstera','Planta brânză'],
   'Southern Mexico to Panama (Central America)', 'High (tropical rainforest)',
   'Tropical rainforest understorey; hemiepiphytic climber',
   'Up to ~20 m as a climber in habitat; commonly 2–3 m indoors', 'Fast', 'Long-lived (decades)',
   true, 'Rarely flowers indoors; a spadix-and-spathe inflorescence in habitat',
   'Edible fruit that ripens over ~1 year; unripe fruit contains irritant calcium oxalate',
   'Ripe fruit is fragrant, with pineapple-banana notes',
   'Large, up to 60–90 cm long on mature plants', 'Heart-shaped, becoming pinnately fenestrated (split) with age',
   'Deep green', 'Leathery', 'Species is plain green; variegated cultivars such as ''Thai Constellation'' and ''Albo Variegata'' exist',
   'Glossy', 'Aerial roots plus fibrous roots (hemiepiphyte)',
   'Readily grown from stem cuttings with at least one node (ideally an aerial root too); roots in water or moist substrate. Air-layering also works.',
   'Prune in spring or summer to control size, cutting just above a node. Aerial roots can be tucked into the pot or left. The sap is irritant — wear gloves.',
   ARRAY['Spring: repot if rootbound, resume feeding','Summer: add a moss pole for support, wipe the leaves','Autumn: reduce feeding as growth slows','Winter: water less and keep away from cold draughts'],
   '{"March":"Repot if rootbound and resume feeding","June":"Peak growth — provide a moss pole","September":"Slow down feeding","December":"Reduce watering, avoid cold windows"}'::jsonb,
   '[{"q":"Why isn''t my Monstera splitting?","a":"Young leaves are naturally entire; the holes and splits (fenestration) develop with maturity and enough light. Bright indirect light and a support to climb encourage splitting."},{"q":"Is Monstera toxic?","a":"Yes — every part contains insoluble calcium oxalate crystals that irritate the mouth and digestive tract of pets and children if chewed."}]'::jsonb,
   ARRAY['The name does not mean it is a "monster" plant — it refers to the unusual, monstrous-looking perforated leaves.','It is often sold as a "split-leaf philodendron", but it is not a Philodendron.'],
   ARRAY['The species epithet "deliciosa" refers to its edible, pineapple-like fruit.','The leaf fenestrations are thought to help the plant shed wind and let light reach lower leaves.'],
   ARRAY['RHS','Missouri Botanical Garden','Kew — Plants of the World Online']),

  ('ficus-lyrata', 'Fiddle-leaf fig', 'Ficus lyrata',
   ARRAY['Banjo fig'], 'Moraceae', 'Ficus', 'lyrata',
   ARRAY['Ficus lyrata','Smochin cu frunze de vioară'],
   'Western Africa (lowland tropical rainforest)', 'High',
   'Tropical rainforest; can begin life as an epiphyte (strangler-type Ficus)',
   'Up to ~12–15 m in habitat; 1–3 m indoors', 'Moderate', 'Long-lived',
   true, null, 'Produces figs in habitat; rarely fruits indoors', null,
   'Large, 20–45 cm long', 'Fiddle- or lyre-shaped (broad at the tip, waisted)',
   'Deep green with prominent pale veins', 'Leathery and stiff',
   'Usually plain green; a variegated cultivar exists', 'Glossy', null,
   'Grown from stem or leaf-bud cuttings and by air-layering; exudes white latex when cut.',
   'Prune in spring to shape and encourage branching; pinch the growing tip. The latex sap is irritant.',
   ARRAY['Spring: repot if needed, resume feeding','Summer: rotate for even growth, shield from hot sun through glass','Autumn/Winter: reduce water, avoid cold draughts and sudden moves'],
   null,
   '[{"q":"Why is my fiddle-leaf fig dropping leaves?","a":"Most often from sudden change — a draught, being relocated, or over- or under-watering. It prefers a stable, bright spot and consistent care."}]'::jsonb,
   null,
   ARRAY['The Latin "lyrata" refers to the lyre-shaped leaves.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('sansevieria-trifasciata', 'Snake plant', 'Dracaena trifasciata',
   ARRAY['Sansevieria trifasciata','Mother-in-law''s tongue','Saint George''s sword'],
   'Asparagaceae', 'Dracaena', 'trifasciata', ARRAY['Limba soacrei','Sansevieria'],
   'Tropical West Africa (Nigeria to the Congo)', 'Low to moderate',
   'Arid, rocky tropical scrub',
   'Leaves to ~0.7–1.2 m tall', 'Slow', 'Long-lived',
   true, 'Occasionally sends up a spike of greenish-white flowers', null,
   'The flowers are fragrant, especially at night',
   null, 'Erect, stiff, sword-shaped', 'Dark green with pale grey-green cross-banding',
   'Thick, rigid, semi-succulent', 'The cultivar ''Laurentii'' has yellow leaf margins', null, 'Rhizome',
   'Propagated by dividing the rhizome or by leaf cuttings; note that leaf cuttings of variegated forms revert to plain green.',
   'Little pruning needed; remove damaged leaves at the base.',
   ARRAY['Spring–Summer: water only when the soil is dry, feed lightly','Autumn–Winter: water sparingly (roughly monthly), keep above 10°C'],
   null,
   '[{"q":"How often should I water a snake plant?","a":"Sparingly. Let the soil dry out fully between waterings; it is very drought-tolerant and far more likely to die from overwatering than from neglect."},{"q":"Does it really clean the air?","a":"It featured in a 1989 NASA sealed-chamber study, but the air-cleaning effect in a normal ventilated room is negligible. Enjoy it as a resilient plant, not an air purifier."}]'::jsonb,
   ARRAY['Marketing often claims snake plants "purify" household air; real-world air cleaning by houseplants is negligible at room scale.'],
   ARRAY['It uses CAM photosynthesis, taking in CO2 at night, which makes it exceptionally drought-tolerant.','It was recently reclassified from the genus Sansevieria into Dracaena.'],
   ARRAY['RHS','Missouri Botanical Garden','Kew — Plants of the World Online']),

  ('epipremnum-aureum', 'Golden pothos', 'Epipremnum aureum',
   ARRAY['Pothos','Devil''s ivy','Money plant'],
   'Araceae', 'Epipremnum', 'aureum', ARRAY['Pothos','Iedera diavolului'],
   'Native to French Polynesia (Society Islands); naturalised across the tropics', 'High',
   'Tropical forest; hemiepiphytic climber',
   'Climbs 12–20 m in the tropics; trails 1–3 m indoors', 'Fast', 'Long-lived',
   true, null, null, null,
   null, 'Heart-shaped; becomes large and pinnately lobed when mature and climbing',
   'Green marbled with yellow or cream', null,
   'Golden, white or marble variegation depending on cultivar; brighter light retains variegation', 'Glossy, waxy',
   'Aerial roots plus fibrous roots',
   'One of the easiest plants to propagate — stem cuttings with a node root readily in water or soil.',
   'Trim any time to control length and encourage bushiness; cut just below a node.',
   ARRAY['Spring–Summer: main growth, feed monthly','Autumn–Winter: water less as growth slows'],
   null,
   '[{"q":"Why is my pothos losing its variegation?","a":"Usually too little light. Move it somewhere brighter (indirect) and the new growth will carry more variegation."},{"q":"Is pothos toxic?","a":"Yes — it contains insoluble calcium oxalate crystals; keep it away from pets and children who might chew it."}]'::jsonb,
   ARRAY['The name "devil''s ivy" comes from it being nearly impossible to kill and staying green even in low light.'],
   ARRAY['It very rarely flowers; for a long time wild plants were known only in their juvenile form.','Naturalised pothos is considered invasive in some tropical regions.'],
   ARRAY['RHS','Missouri Botanical Garden','Kew — Plants of the World Online']),

  ('zamioculcas-zamiifolia', 'ZZ plant', 'Zamioculcas zamiifolia',
   ARRAY['Zanzibar gem','Emerald palm','Aroid palm'],
   'Araceae', 'Zamioculcas', 'zamiifolia', ARRAY['Zamioculcas','Planta ZZ'],
   'Eastern Africa (Kenya to northeastern South Africa)', 'Low to moderate',
   'Dry grassland and forest, seasonally dry',
   '0.45–1 m', 'Slow', 'Long-lived',
   true, null, null, null,
   null, 'Pinnate leaves lined with oval leaflets', 'Dark green (the cultivar ''Raven'' is near-black)',
   'Thick, waxy, semi-succulent', null, 'Very glossy', 'Rhizome with water-storing tubers',
   'Propagated by division or by leaflet cuttings, which slowly form a tuber; patience is required.',
   'Minimal pruning; remove yellowed stems at the base.',
   ARRAY['Spring–Summer: water when dry, feed occasionally','Autumn–Winter: water rarely; it tolerates neglect'],
   null,
   '[{"q":"How often should I water a ZZ plant?","a":"Rarely — its rhizomes store water. Let the soil dry out; overwatering causes rhizome rot."},{"q":"Is the ZZ plant poisonous?","a":"It contains calcium oxalate and is mildly toxic if eaten, and the sap can irritate skin. Handle it sensibly around pets and children."}]'::jsonb,
   ARRAY['A persistent myth calls the ZZ plant dangerously poisonous or even carcinogenic — in reality it is only mildly toxic if eaten, like many aroids, and safe to keep and handle sensibly.'],
   ARRAY['Its water-storing rhizomes make it one of the most drought-tolerant foliage houseplants.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('spathiphyllum-wallisii', 'Peace lily', 'Spathiphyllum wallisii',
   ARRAY['White sails','Spathe flower'],
   'Araceae', 'Spathiphyllum', 'wallisii', ARRAY['Crinul păcii','Spatifilum'],
   'Tropical Central and South America', 'High',
   'Tropical rainforest floor',
   '0.4–0.6 m', 'Moderate', null,
   true, 'Can flower on and off through the year, mainly in spring', null,
   'The flowers are lightly fragrant',
   null, 'Lance-shaped', 'Dark green', null, null, 'Glossy', null,
   'Propagated by dividing the clump in spring.',
   'Remove spent flower stalks and yellowing leaves at the base.',
   ARRAY['Spring–Summer: keep evenly moist, feed monthly','Autumn–Winter: reduce feeding, keep warm and humid'],
   null,
   '[{"q":"Why are the flowers turning green?","a":"The white spathe naturally ages to green. Cutting the old stalk off at the base tidies the plant."},{"q":"Why does my peace lily droop?","a":"It wilts dramatically when dry but usually recovers quickly after watering. Persistent drooping can signal over- or under-watering."}]'::jsonb,
   ARRAY['It is often marketed as an air-purifying plant, but the effect in a real room is negligible.'],
   ARRAY['The showy white "flower" is a spathe (a modified leaf) that wraps around the true tiny flowers on the spadix.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('aloe-vera', 'Aloe vera', 'Aloe vera',
   ARRAY['Aloe barbadensis','True aloe','Medicinal aloe'],
   'Asphodelaceae', 'Aloe', 'vera', ARRAY['Aloe vera'],
   'Arabian Peninsula; widely cultivated and naturalised in arid regions', 'Low (arid)',
   'Arid, well-drained rocky ground',
   '0.6–1 m', 'Slow to moderate', null,
   true, 'Tubular yellow flowers on a tall spike in summer on mature plants', null, null,
   null, 'Thick, fleshy, lance-shaped leaves in a rosette with toothed margins',
   'Grey-green, sometimes spotted when young', 'Succulent', null, null, 'Shallow and spreading',
   'Propagated by removing the offsets ("pups") that form around the base.',
   'Remove old outer leaves at the base as needed.',
   ARRAY['Spring–Summer: water when the soil is fully dry, give bright light','Autumn–Winter: water minimally, keep frost-free'],
   null,
   '[{"q":"Can I put the gel on my skin?","a":"The clear inner-leaf gel is widely used on minor skin irritation. The yellow latex just under the skin is a strong laxative and irritant — avoid it."}]'::jsonb,
   ARRAY['While the gel soothes minor burns, aloe vera is not a cure-all; strong medicinal claims are largely unproven.'],
   ARRAY['Like many succulents it uses CAM photosynthesis, opening its pores at night to conserve water.'],
   ARRAY['RHS','Missouri Botanical Garden','Kew — Plants of the World Online']),

  ('chlorophytum-comosum', 'Spider plant', 'Chlorophytum comosum',
   ARRAY['Ribbon plant','Airplane plant','Hen and chickens'],
   'Asparagaceae', 'Chlorophytum', 'comosum', ARRAY['Planta păianjen','Clorofitum'],
   'Coastal southern Africa', 'Moderate',
   'Forest floor and coastal scrub',
   '0.2–0.3 m of foliage, with long trailing plantlet stems', 'Fast', null,
   true, 'Small white star-shaped flowers on arching stems', null, null,
   null, 'Long, narrow, arching, strap-like', 'Green, often with a central or marginal cream/white stripe',
   null, 'The cultivars ''Vittatum'' (central white stripe) and ''Variegatum'' (white margins) are common', null,
   'Fleshy, water-storing tuberous roots',
   'Extremely easy — pot up the plantlets ("spiderettes") that form on the arching stems, or divide the clump.',
   'Remove browned leaf tips and spent runners as desired.',
   ARRAY['Spring–Summer: keep moist, feed monthly, produces plantlets','Autumn–Winter: water less'],
   null,
   '[{"q":"Why do the leaf tips go brown?","a":"Commonly from fluoride or chlorine in tap water, dry air, or salt build-up from fertiliser. Filtered water and occasionally flushing the soil help."}]'::jsonb,
   null,
   ARRAY['One of the most productive houseplants for offsets, which makes it very easy to share.','It is considered non-toxic to cats and dogs, unlike many popular houseplants.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('dracaena-marginata', 'Madagascar dragon tree', 'Dracaena marginata',
   ARRAY['Dragon tree','Dracaena reflexa var. angustifolia'],
   'Asparagaceae', 'Dracaena', 'marginata', ARRAY['Dracena','Arborele dragon'],
   'Madagascar', 'Moderate', null,
   'Up to 2–3 m indoors', 'Slow', null,
   true, null, null, null,
   null, 'Narrow, arching, sword-shaped leaves clustered at the stem tips', 'Green with red-purple margins',
   null, 'Cultivars such as ''Tricolor'' and ''Colorama'' add cream and pink stripes', null, null,
   'Propagated from stem-tip or stem-section cuttings.',
   'Cut back tall canes in spring; the plant branches out from below the cut.',
   ARRAY['Spring–Summer: water when the top few cm are dry, feed occasionally','Autumn–Winter: water sparingly, keep warm'],
   null,
   '[{"q":"Why are the leaf tips browning?","a":"Dracaenas are sensitive to fluoride and salts in tap water and to dry air; filtered water and moderate humidity help."}]'::jsonb,
   null,
   null,
   ARRAY['RHS','Missouri Botanical Garden']),

  ('philodendron-hederaceum', 'Heartleaf philodendron', 'Philodendron hederaceum',
   ARRAY['Philodendron scandens','Sweetheart plant'],
   'Araceae', 'Philodendron', 'hederaceum', ARRAY['Filodendron'],
   'Central America, the Caribbean and tropical South America', 'High',
   'Tropical rainforest; hemiepiphytic climber',
   'Trails or climbs several metres', 'Fast', null,
   true, null, null, null,
   null, 'Heart-shaped', 'Glossy deep green (cultivars ''Brasil'' and ''Lemon Lime'' are variegated or chartreuse)',
   null, null, 'Glossy', 'Aerial and fibrous roots',
   'Very easy from stem cuttings with a node, in water or soil.',
   'Pinch and trim to keep it bushy; cut above a node.',
   ARRAY['Spring–Summer: main growth, feed monthly','Autumn–Winter: water less, growth slows'],
   null,
   '[{"q":"How is it different from pothos?","a":"They look alike but differ: philodendron leaves are thinner and softer with a finer drip tip, and new growth emerges from a papery sheath (cataphyll); pothos leaves are thicker and waxier."},{"q":"Is it toxic?","a":"Yes — like other aroids it contains insoluble calcium oxalate and is toxic to pets and children if chewed."}]'::jsonb,
   null,
   null,
   ARRAY['RHS','Missouri Botanical Garden']),

  ('ficus-elastica', 'Rubber plant', 'Ficus elastica',
   ARRAY['Rubber fig','India rubber tree','Rubber bush'],
   'Moraceae', 'Ficus', 'elastica', ARRAY['Ficus','Arborele de cauciuc'],
   'Northeast India to Southeast Asia (Sumatra, Java)', 'High',
   'Tropical rainforest; can grow as a strangler epiphyte',
   'Over 30 m in habitat; 1–3 m indoors', 'Moderate to fast', null,
   true, null, null, null,
   'Large, 10–30 cm', 'Broad oval with a pointed tip',
   'Deep glossy green; burgundy and variegated cultivars exist (''Burgundy'', ''Tineke'', ''Ruby'')',
   'Thick and leathery', null, 'Glossy', null,
   'Propagated by stem-tip cuttings and by air-layering; it exudes white latex.',
   'Prune in spring to control height and encourage branching; the latex is irritant.',
   null, null,
   '[{"q":"Is the sap dangerous?","a":"The milky latex can irritate skin and is mildly toxic if ingested; wipe cut stems and wash your hands."}]'::jsonb,
   null,
   ARRAY['Its latex was once a commercial source of rubber, later eclipsed by the Pará rubber tree (Hevea brasiliensis).','In parts of India its aerial roots are trained across rivers to form living root bridges.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('calathea-orbifolia', 'Calathea orbifolia', 'Goeppertia orbifolia',
   ARRAY['Calathea orbifolia','Round-leaf calathea'],
   'Marantaceae', 'Goeppertia', 'orbifolia', ARRAY['Calathea'],
   'Bolivia', 'High',
   'Tropical rainforest understorey',
   '~0.6–1 m', 'Moderate', null,
   true, null, null, null,
   'Large and rounded, to ~30 cm', 'Broadly oval to round',
   'Pale green with silvery-green stripes', 'Thin', null, null, null,
   'Propagated by dividing the clump.',
   'Remove damaged leaves at the base.',
   ARRAY['Year-round: keep warm, humid and evenly moist; avoid cold draughts and direct sun'],
   null,
   '[{"q":"Why are the leaf edges browning and curling?","a":"Plants in the prayer-plant family are thirsty for humidity and sensitive to hard tap water. Use filtered or rainwater, keep humidity high, and never let the soil dry out fully."}]'::jsonb,
   null,
   ARRAY['Prayer-plant relatives raise and lower their leaves on a daily rhythm (nyctinasty), driven by a swollen joint called a pulvinus.','It is non-toxic to cats and dogs.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('chamaedorea-elegans', 'Parlour palm', 'Chamaedorea elegans',
   ARRAY['Parlor palm','Neanthe bella palm'],
   'Arecaceae', 'Chamaedorea', 'elegans', ARRAY['Palmier de cameră'],
   'Rainforests of southern Mexico and Guatemala', 'High',
   'Tropical rainforest understorey',
   '~1–2 m indoors', 'Slow', null,
   true, 'Small yellow bead-like flowers on mature plants', null, null,
   null, 'Pinnate (feather) fronds', 'Green', null, null, null, null,
   'Grown from seed; established clumps can sometimes be divided. It is not grown from cuttings.',
   'Only remove dead fronds — palms do not regrow from a cut stem.',
   null, null,
   '[{"q":"Why are the frond tips brown?","a":"Usually dry air or under-watering. Keep the humidity up and the soil lightly moist, and avoid direct sun."}]'::jsonb,
   null,
   ARRAY['A Victorian favourite for shady "parlours", prized for tolerating low light.','It is listed as non-toxic to cats and dogs.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('hedera-helix', 'English ivy', 'Hedera helix',
   ARRAY['Common ivy','European ivy'],
   'Araliaceae', 'Hedera', 'helix', ARRAY['Iederă'],
   'Europe and western Asia', 'Moderate',
   'Woodland; climbs trees and walls by adventitious rootlets',
   'Climbs 20–30 m', 'Fast and vigorous', 'Long-lived',
   true, 'Greenish-yellow umbels in autumn on adult, non-climbing growth', 'Black berries follow the flowers; toxic if eaten', null,
   null, 'Lobed on juvenile growth; entire and ovate on adult flowering growth',
   'Dark green, often variegated in cultivars', null,
   'Many variegated cultivars in cream, gold or silver', 'Glossy',
   'Fibrous, with climbing adventitious rootlets along the stems',
   'Very easy from stem cuttings.',
   'Trim freely to control its vigorous growth.',
   null, null,
   '[{"q":"Is English ivy invasive?","a":"Outdoors in some regions (for example parts of North America) it is an aggressive invasive weed that smothers native plants — check local guidance before planting it out."}]'::jsonb,
   ARRAY['Ivy is not parasitic and does not feed on or "strangle" a healthy tree, though heavy growth can shade its foliage and add weight and wind resistance.'],
   ARRAY['Its climbing rootlets secrete a natural adhesive that has inspired bio-adhesive research.','Late-season ivy flowers are an important nectar source for insects.'],
   ARRAY['RHS','Missouri Botanical Garden']),

  ('crassula-ovata', 'Jade plant', 'Crassula ovata',
   ARRAY['Money plant','Money tree','Lucky plant','Friendship tree'],
   'Crassulaceae', 'Crassula', 'ovata', ARRAY['Arborele de jad','Copacul banilor'],
   'South Africa and Mozambique', 'Low (arid)',
   'Dry, rocky slopes and scrub',
   '1–2.5 m over many years', 'Slow', 'Long-lived (can live for decades)',
   true, 'Clusters of small white-pink star flowers in winter on mature plants given a cool, dry rest', null, null,
   null, 'Oval, fleshy leaves', 'Glossy green, often red-edged in strong light',
   'Succulent', null, 'Glossy', null,
   'Very easy from leaf or stem cuttings — let the cut callus for a day or two, then pot in a gritty mix.',
   'Prune in spring to shape it into a tree form; the cuttings root easily.',
   ARRAY['Spring–Summer: water when the soil is dry, give bright light','Autumn–Winter: keep cool and nearly dry to encourage flowering'],
   null,
   '[{"q":"How much should I water a jade?","a":"Sparingly. Let the soil dry out fully; the fleshy leaves store water and the plant rots easily if kept wet."}]'::jsonb,
   ARRAY['It is widely regarded in feng shui as a symbol of luck and prosperity — folklore, not horticulture.'],
   ARRAY['It uses CAM photosynthesis; the leaves can develop red margins under bright light and cool nights.'],
   ARRAY['RHS','Missouri Botanical Garden'])
on conflict (slug) do nothing;
