import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

function htmlWrapper(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} — PRV House</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
      font-size: 14px;
      line-height: 1.6;
      color: #1a1a1a;
      background: #fff;
      padding: 48px;
      max-width: 720px;
      margin: 0 auto;
    }
    @media print {
      body { padding: 0; }
      .no-print { display: none !important; }
    }
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      border-bottom: 2px solid #1a1a1a;
      padding-bottom: 16px;
      margin-bottom: 32px;
    }
    .brand {
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: #555;
    }
    .doc-title {
      font-size: 22px;
      font-weight: 700;
      margin-bottom: 24px;
    }
    .section { margin-bottom: 20px; }
    .label {
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: #666;
      margin-bottom: 4px;
    }
    .value { font-size: 14px; color: #1a1a1a; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }
    .divider { border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }
    .amount-box {
      background: #f5f5f5;
      border-left: 4px solid #1a1a1a;
      padding: 16px 20px;
      margin: 20px 0;
      border-radius: 0 8px 8px 0;
    }
    .amount-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #666; }
    .amount-value { font-size: 28px; font-weight: 700; margin-top: 4px; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e0e0e0;
      font-size: 11px;
      color: #999;
      text-align: center;
    }
    .print-btn {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      background: #1a1a1a;
      color: #fff;
      border: none;
      border-radius: 8px;
      padding: 10px 20px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      margin-bottom: 32px;
    }
    .print-btn:hover { background: #333; }
    .notice-box {
      background: #fffbeb;
      border: 1px solid #fcd34d;
      border-radius: 8px;
      padding: 16px;
      margin: 20px 0;
    }
  </style>
</head>
<body>
  <div class="no-print" style="margin-bottom:24px;">
    <button class="print-btn" onclick="window.print()">
      🖨️ Print / Save as PDF
    </button>
  </div>
  <div class="header">
    <span class="brand">PRV House</span>
    <span class="brand">${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
  </div>
  ${body}
  <div class="footer">
    Generated by PRV House · ${new Date().toISOString().split('T')[0]}
  </div>
</body>
</html>`
}

export async function GET(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return new NextResponse('Unauthorized', { status: 401 })
  }

  const { searchParams } = new URL(request.url)
  const type = searchParams.get('type')
  const leaseId = searchParams.get('lease_id')
  const dateParam = searchParams.get('date')
  const descriptionParam = searchParams.get('description')
  const monthParam = searchParams.get('month') // YYYY-MM

  if (type === 'rent_receipt') {
    if (!leaseId) {
      return new NextResponse('lease_id required', { status: 400 })
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: lease } = await (supabase as any)
      .from('leases')
      .select('id, monthly_rent, currency, property_id, tenant_name, tenant_email')
      .eq('id', leaseId)
      .single()

    if (!lease) {
      return new NextResponse('Lease not found', { status: 404 })
    }

    // Fetch property
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const propRes = await (supabase as any)
      .from('properties')
      .select('id, name, address_line1, city, country')
      .eq('id', lease.property_id)
      .single()
    const prop = propRes.data as { name: string; address_line1: string; city: string } | null

    // Get period label
    const period = monthParam ?? new Date().toISOString().slice(0, 7)
    const [periodYear, periodMonth] = period.split('-')
    const periodLabel = new Date(parseInt(periodYear ?? '2024'), parseInt(periodMonth ?? '1') - 1, 1).toLocaleDateString('en', { month: 'long', year: 'numeric' })

    const refNumber = `${period.replace('-', '')}-${leaseId.slice(0, 8).toUpperCase()}`
    const amount = lease.monthly_rent ?? 0
    const currency = lease.currency ?? 'EUR'
    const sym = currency === 'USD' ? '$' : currency === 'GBP' ? '£' : '€'

    const body = `
      <h1 class="doc-title">Rent Receipt</h1>
      <div class="grid">
        <div class="section">
          <div class="label">Property</div>
          <div class="value">${prop?.name ?? 'N/A'}</div>
          <div class="value" style="color:#666">${prop?.address_line1 ?? ''}, ${prop?.city ?? ''}</div>
        </div>
        <div class="section">
          <div class="label">Tenant</div>
          <div class="value">${lease.tenant_name ?? 'N/A'}</div>
          ${lease.tenant_email ? `<div class="value" style="color:#666">${lease.tenant_email}</div>` : ''}
        </div>
      </div>
      <hr class="divider" />
      <div class="amount-box">
        <div class="amount-label">Amount received</div>
        <div class="amount-value">${sym}${amount.toLocaleString('en', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
      </div>
      <div class="grid">
        <div class="section">
          <div class="label">Rental period</div>
          <div class="value">${periodLabel}</div>
        </div>
        <div class="section">
          <div class="label">Payment date</div>
          <div class="value">${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
        </div>
      </div>
      <div class="section">
        <div class="label">Reference number</div>
        <div class="value" style="font-family:monospace;font-size:13px">${refNumber}</div>
      </div>
      <hr class="divider" />
      <div class="section">
        <p style="color:#555;font-size:13px">This receipt confirms that the above rental payment has been received in full for the period stated. Please retain this document for your records.</p>
      </div>
    `

    return new NextResponse(htmlWrapper('Rent Receipt', body), {
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  if (type === 'inspection_notice') {
    if (!leaseId) {
      return new NextResponse('lease_id required', { status: 400 })
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: lease } = await (supabase as any)
      .from('leases')
      .select('id, property_id, tenant_name')
      .eq('id', leaseId)
      .single()

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const propRes2 = await (supabase as any)
      .from('properties')
      .select('id, name, address_line1, city, country')
      .eq('id', lease?.property_id ?? '')
      .single()
    const prop = propRes2.data as { name: string; address_line1: string; city: string; country: string } | null

    const inspectionDate = dateParam ?? new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
    const inspectionDateLabel = new Date(inspectionDate + 'T00:00:00').toLocaleDateString('en-GB', {
      weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
    })

    const body = `
      <h1 class="doc-title">Notice of Property Inspection</h1>
      <div class="section">
        <div class="label">Date of notice</div>
        <div class="value">${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
      </div>
      <div class="section">
        <div class="label">To (Tenant)</div>
        <div class="value">${lease?.tenant_name ?? 'Tenant'}</div>
      </div>
      <div class="section">
        <div class="label">Property address</div>
        <div class="value">${prop?.address_line1 ?? ''}, ${prop?.city ?? ''}, ${prop?.country ?? ''}</div>
      </div>
      <hr class="divider" />
      <div class="notice-box">
        <p style="font-weight:600;margin-bottom:8px">Notice of routine property inspection</p>
        <p>Please be advised that a routine inspection of the above-mentioned property will take place on:</p>
        <p style="font-weight:700;font-size:16px;margin:12px 0">${inspectionDateLabel}</p>
        <p>This notice is provided in accordance with your tenancy agreement, giving the required minimum 48 hours notice.</p>
      </div>
      <div class="section">
        <p style="color:#555;font-size:13px">The inspection will be conducted by the landlord/property manager and is expected to take approximately 30–45 minutes. You are welcome to be present during the inspection.</p>
        <p style="color:#555;font-size:13px;margin-top:8px">If you have any questions or would like to reschedule, please contact us as soon as possible.</p>
      </div>
      <hr class="divider" />
      <div class="section">
        <div class="label">Landlord / Agent</div>
        <div class="value">PRV House Management</div>
      </div>
    `

    return new NextResponse(htmlWrapper('Inspection Notice', body), {
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  if (type === 'maintenance_notice') {
    const description = descriptionParam ?? 'scheduled maintenance work'
    const maintenanceDate = dateParam ?? new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
    const maintenanceDateLabel = new Date(maintenanceDate + 'T00:00:00').toLocaleDateString('en-GB', {
      weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
    })

    // Get property from lease_id if provided, else skip
    let propertyAddress = 'the property'
    if (leaseId) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: lease } = await (supabase as any)
        .from('leases')
        .select('property_id')
        .eq('id', leaseId)
        .single()
      if (lease) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const propRes3 = await (supabase as any)
          .from('properties')
          .select('address_line1, city')
          .eq('id', lease.property_id)
          .single()
        const prop = propRes3.data as { address_line1: string; city: string } | null
        if (prop) propertyAddress = `${prop.address_line1}, ${prop.city}`
      }
    }

    const body = `
      <h1 class="doc-title">Notice of Maintenance Work</h1>
      <div class="section">
        <div class="label">Date of notice</div>
        <div class="value">${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
      </div>
      <div class="section">
        <div class="label">Property address</div>
        <div class="value">${propertyAddress}</div>
      </div>
      <hr class="divider" />
      <div class="notice-box">
        <p style="font-weight:600;margin-bottom:8px">Notice of planned maintenance work</p>
        <p>We wish to inform you that the following maintenance work has been scheduled at the property:</p>
        <p style="font-weight:700;font-size:15px;margin:12px 0">${description}</p>
        <p>This work is scheduled for:</p>
        <p style="font-weight:700;font-size:16px;margin:12px 0">${maintenanceDateLabel}</p>
      </div>
      <div class="section">
        <p style="color:#555;font-size:13px">We apologise for any inconvenience this may cause. Our contractors will endeavour to minimise disruption and complete the work as efficiently as possible.</p>
        <p style="color:#555;font-size:13px;margin-top:8px">If you have any questions or concerns, please do not hesitate to contact us.</p>
      </div>
      <hr class="divider" />
      <div class="section">
        <div class="label">Landlord / Agent</div>
        <div class="value">PRV House Management</div>
      </div>
    `

    return new NextResponse(htmlWrapper('Maintenance Notice', body), {
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  return new NextResponse('Invalid template type. Use: rent_receipt, inspection_notice, or maintenance_notice', {
    status: 400,
  })
}
